// "use client";
import type {Metadata, ResolvingMetadata} from "next";
import "@style/globals.css";
import {useEffect} from "react";
import store, {persistor} from "@/store";
import Head from "next/head";
// import {PersistGate} from "redux-persist/integration/react";

// console.log("lay");

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// export async function generateMetadata({params, searchParams}: Props, parent: ResolvingMetadata): Promise<Metadata> {
// 	return {
// 		title: "dynamic title",
// 	};
// }

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
